### ISSUE TITLE
'once' method is missing

### ISSUE THREAD

**Issue by bluzi** [bougarfaoui/ng-socket-io#10]
Hi,

I've noticed your module is missing the 'once' method from the original socket.io
Any chance you'll be adding it anytime soon? Can I make the change and create a pull request?

**Comment by bougarfaoui** [comment]
yeah of course your pull request will be highly appreciated.

**Comment by bluzi** [comment]
Thanks, but I'm trying to push my commit to a separate branch, but it seems like I'm not permitted

**Comment by bougarfaoui** [comment]
I don't know what is the problem

**Comment by bluzi** [comment]
Alright, so I've managed to create a pull request. Turns out it was my bad.

**Comment by bougarfaoui** [comment]
thanks, it's your pull request has been merged. sorry for being late.
