### ISSUE TITLE
ERROR in Error encountered resolving symbol values statically

### ISSUE THREAD

**Issue by di3orlive** [bougarfaoui/ng-socket-io#16]
how i can fix this ?
```
ERROR in Error encountered resolving symbol values statically. Calling function 'makeDecorator', function 
calls are not supported. Consider replacing the function or lambda with a reference to an exported 
function, resolving symbol Injectable in D:/PROJECTS/O4P/node_modules/ng2-socket-
io/node_modules/@angular/core/src/di/metadata.d.ts, resolving symbol OpaqueToken in 
D:/PROJECTS/O4P/node_modules/ng2-socket-io/node_modules/@angular/core/src/di/opaque_token.d.ts, 
resolving symbol OpaqueToken in D:/PROJECTS/O4P/node_modules/ng2-socket-
io/node_modules/@angular/core/src/di/opaque_token.d.ts

ERROR in ./src/main.ts
Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory' in 'D:\PROJECTS\O4P\src'
@ ./src/main.ts 5:0-74
@ multi ./src/main.ts
```

**Comment by Limoli** [comment]
Please, follow my request with the same error here #6 .

**Comment by di3orlive** [comment]
@Limoli I have decided to remove this module and use this http://www.syntaxsuccess.com/viewarticle/socket.io-with-rxjs-in-angular-2.0

**Comment by Limoli** [comment]
@di3orlive Thank you for your comment. I will try it. Is it working on Ionic in production (--prod) mode?

**Comment by di3orlive** [comment]
@Limoli I think yes. There should be no problem with this.
also don't forget about typings 
npm install @types/socket.io-client --save

**Comment by Limoli** [comment]
@di3orlive Have you tried to compile it on Ionic? It seems don't work. I haven't the previous error in production way, but it doesn't work in both modes (development / production). If I serve the application in web browser it goes good.

**Comment by di3orlive** [comment]
@Limoli 'on Ionic?' 
not yet

**Comment by bougarfaoui** [comment]
Hi guys sorry for being late , I just updated the module , I think the problem with Ionic is fixed and I it worked just fine for me.

**Comment by KevinBeckers** [comment]
Same issue:

@angular/cli: 1.4.3
node: 7.2.1
os: darwin x64
@angular/animations: 4.4.6
@angular/common: 4.4.6
@angular/compiler: 4.4.6
@angular/core: 4.4.6
@angular/forms: 4.4.6
@angular/http: 4.4.6
@angular/platform-browser: 4.4.6
@angular/platform-browser-dynamic: 4.4.6
@angular/router: 4.4.6
@angular/cli: 1.4.3
@angular/compiler-cli: 4.4.6
@angular/language-service: 4.4.6
typescript: 2.3.4

**Comment by bougarfaoui** [comment]
which version are you using ?

**Comment by KevinBeckers** [comment]
Lates NPM version (0.2.0).
https://www.npmjs.com/package/ng-socket-io

**Comment by bougarfaoui** [comment]
this is an known issue in @angular/cli [https://github.com/angular/angular-cli/issues/3707](3707)
