### ISSUE TITLE
АОТ Warning: Can't resolve all parameters for WrappedSocket

### ISSUE THREAD

**Issue by ilianiv** [bougarfaoui/ng-socket-io#17]
Hello,

Building AOT using angular/cli@1.2.0 gives me a warning:
```
Warning: Can't resolve all parameters for WrappedSocket in <my_project_path>/node_modules/ng-socket-io/socket-io.service.ts: (?). This will become an error in Angular v5.x
```

Here is my `app.module.ts`
```
...
const ioConfig: SocketIoConfig = { url : CONFIG.io.url, options : CONFIG.io.options };

@NgModule({
  declarations : [ ... ],
  imports      : [
    ...
    SocketIoModule.forRoot(ioConfig),
    ...
  ],
  bootstrap    : [ ... ],
  providers    : [ ... ]
})
export class AppModule {
}

```

**Comment by ilianiv** [comment]
Angular is at [5.0.0-beta.1](https://github.com/angular/angular/releases/tag/5.0.0-beta.1) now. Any progress here?

**Comment by alan-agius4** [comment]
Fixed in https://github.com/bougarfaoui/ng-socket-io/pull/18#issuecomment-320534770

**Comment by bougarfaoui** [comment]
thanks to @alan-agius4  it's fixed now. I will close it feel free to open it again if there is a problem.
