### ISSUE TITLE
not able to run angular2 project which is public

### ISSUE THREAD

**Issue by Mohinesh27** [bougarfaoui/ng-socket-io#20]
I have successfully run the server project but when I am trying to run the angular2 project it gives me below error-

You have to be inside an angular-cli project in order to use the build command.

for more details I have attached snapshot.
![error socket io with angularjs](https://user-images.githubusercontent.com/6978930/29549920-8676d634-8728-11e7-8a50-3904cb607988.PNG)

Thanks in Advance,
Mohinesh

**Comment by bougarfaoui** [comment]
Hi @Mohinesh27  this is not an issue with ng-socket-io module, you're getting this error because you're running `ng serve` command outside the angular project.
