### ISSUE TITLE
NPM update ng-socket-io

### ISSUE THREAD

**Issue by ilianiv** [bougarfaoui/ng-socket-io#21]
Hi,
I'm a little bit confused about ng-socket-io versions.  `npm outdated` says I have installed 0.1.91 but the latest version is lower - 0.1.11. [Releases page](https://github.com/bougarfaoui/ng-socket-io/releases) displays 0.1.7 as latest version.

![image](https://user-images.githubusercontent.com/3925630/29553067-7812c3b0-8722-11e7-959d-2f0911685d04.png)

Here is `/<my_project>/node_modules/ng-socket-io/package.json`
```
...,
"tags": [
    "angular2",
    "socket.io",
    "typescript",
    "angular2-socket.io"
  ],
  "version": "0.1.91"  <---
  ...
```

**Comment by bougarfaoui** [comment]
@ilianiv  you'are right, I'm sorry for this , `0.1.91` was my error. the current and latest version is `0.1.11`. I'm going to update the release Page. thanks.

**Comment by ilianiv** [comment]
@bougarfaoui,
Version `0.1.91` is still on NPM:
```
{ 
  name: 'ng-socket-io',
  description: ...,
  versions:
   [ '0.1.2',
     '0.1.6',
     '0.1.8',
     '0.1.9',
     '0.1.10',
     '0.1.11',
     '0.1.91' ],
  maintainers: ...
```
 and every time I do `npm outdated` ng-socket-io appears as package for update  
![image](https://user-images.githubusercontent.com/3925630/31003562-0ad36594-a4f9-11e7-9625-f4079bc46737.png)
