### ISSUE TITLE
Update Config

### ISSUE THREAD

**Issue by default23** [bougarfaoui/ng-socket-io#22]
Hi!

I have some problem with using this library. In my `app.module.ts` file i'm initializing the module in the way, like this

```typescript
// app.module.ts

const SOCKETIO_CONFIG: SocketIoConfig = {
        options: {
            query: `token=${localStorage.getItem('token')}`
        }
}

@NgModule({
    imports: [SocketIoModule.forRoot(SOCKETIO_CONFIG)]
})
```

I have a login page, where I don't need to connect to the SocketServer, and user doesn't have a token in the `localStorage`. When user receive a token from the API, app will update the localStorage. But when the user is not signed in, app initialize with the NULL value of the token, and after user sign in, app trying to connect to the server using the empty token

Please help me find a way to update the token in the configuration or describe more right way to avoid this problem

**Comment by bougarfaoui** [comment]
Hi @default23 , Unfortunately this is not implemented in this module, but this is my solution to your problem :

```
import { Injectable, NgModule, Inject } from '@angular/core';
import { Socket } from 'ng-socket-io';

@Injectable()
export class SocketOne extends Socket {

    constructor(@Inject("_OPTIONS_") private options) {
        super({ url: 'http://url_one:portOne', options });
    }

}

@Component({
//...
})
export class MyComponent {

    constructor( private socketOne : SocketOne) {}
  ngOnInit(){
     if(/** if no token in the LocalStorage*/){
      // after receiving the token and updating the LocalStorage
        this.socketOne  = new SocketOne({
          query: `token=${localStorage.getItem('token')}`
       })
     }
  }
}

@NgModule({
  declarations: [
    //components
  ],
  imports: [
    SocketIoModule,
    //...
  ],
  providers: [SocketOne,
    {
      provide: '_OPTIONS_',
      useValue: {
        query: `token=${localStorage.getItem('token')}`
      }
    }],
  bootstrap: [/** AppComponent **/]
})
export class AppModule { }
```

**Comment by default23** [comment]
Thanks @bougarfaoui for answer, i've find a temporary way to avoid this problem, but your solution looks better , because in my way i forced to create a `new WrappedSocket ` in every component or service that i need it, it's the wrong way, i know

```typescript
 @Component({
    selector   : 'app-navigation',
    templateUrl: './navigation.component.html',
    styleUrls  : ['./navigation.component.scss']
})
export class NavigationComponent implements OnInit {

    private _socket: WrappedSocket;

    constructor(private _store: Store<AppState>,
                private _dialog: MdDialog,
                private _toast: NotificationsService,
                private _userService: UsersService) {

        this._socket = new WrappedSocket(getSocketIOConfig());
    }

    ngOnInit() {
        this.connectSocket();
    }

    connectSocket() {

        const config = getSocketIOConfig();

        const url: string     = config.url || '';
        const options: any    = config.options || {};
        this._socket.ioSocket = io(url, options);
    }
}
```

I'll try to implement your solution, hope i'ts help me, thanks!

If you have a plans to implement this feature with reconnection with different settings, please tell me, i'll be waiting for this feature

**Comment by bougarfaoui** [comment]
you're welcome bro @default23 , it will be a good idea to implement this feature,I will find a free time to implement it.

**Comment by Paragonid** [comment]
@default23 hi, ran into similar problem, solution is pretty obvious if you are ready to change library architecture a little https://github.com/Paragonid/ng-socket-io/commit/d83072ae92bef8303ebd9d03a85cbaa6a2bd11ff . But i'm not entirely sure if it's pull request worthy. Here's my discussion https://github.com/bougarfaoui/ng-socket-io/issues/48
