### ISSUE TITLE
Update 0.1.11 on npmjs hosting.

### ISSUE THREAD

**Issue by vlikin** [bougarfaoui/ng-socket-io#24]
I see that the version 0.1.11 is not available on npmjs. BY this way ``` "ng-socket-io": "git+ssh://git@github.com/bougarfaoui/ng-socket-io.git#0.1.11",``` TS compiler is not able to find module ng2-socket-io. I see It has been loaded on the file system.

**Comment by bougarfaoui** [comment]
Hi @vlikin the `ng2-socket-io` is deprecated, please use `ng-socket-io` instead.  the latest version of `ng-socket-io` on [npm](https://www.npmjs.com/package/ng-socket-io) is `0.1.11` .
