### ISSUE TITLE
'EventEmitter' is declared but never used.

### ISSUE THREAD

**Issue by Shvembldr** [bougarfaoui/ng-socket-io#29]
Hi! I have ts compiler error:
ERROR in C:/../node_modules/ng-socket-io/socket-io.service.ts (1,22): 'EventEmitter' is declared but never used.
And.. Yes its declared and never used )

**Comment by bougarfaoui** [comment]
yeah  I see, You can go the `/node_modules/ng-socket-io/socket-io.service.ts` file in your project and remove `EventEmitter` from the imports, this will fix the issue for now and  I will update the npm module later .  
Thanks :).

**Comment by bougarfaoui** [comment]
fixed.

**Comment by Shvembldr** [comment]
Thanx!
