### ISSUE TITLE
Support: v 0.2.0

### ISSUE THREAD

**Issue by kyvour** [bougarfaoui/ng-socket-io#33]
As I can see the latest version on npm is 0.2.0 - https://www.npmjs.com/package/ng-socket-io
Also it has some fixes/updates in socket-io.service for fromEvent() method in comparison with the version 0.1.11.

But I don't see any tag, changelog and even the source code with these fixes/updates in this repo.
Is the v. 0.2.0 safe for upgrading from 0.1.11 ?

**Comment by bougarfaoui** [comment]
fixed
