### ISSUE TITLE
Support for Angular 5

### ISSUE THREAD

**Issue by cvile** [bougarfaoui/ng-socket-io#36]
After angular update compile failed to load, not sure what happens. Any ideas ?

![screen shot 2017-11-02 at 12 09 29 pm](https://user-images.githubusercontent.com/3367898/32323025-d4f5b786-bfc6-11e7-9963-4c1b050b2c24.png)

**Comment by cvile** [comment]
ng serve --aot works like a charm

**Comment by vladimirvaca** [comment]
you managed to fix it ??
what is it --aot ??
