### ISSUE TITLE
Property 'fromEvent' does not exists

### ISSUE THREAD

**Issue by ander2** [bougarfaoui/ng-socket-io#37]
After upgrading to `angular5` and `ng-socket-io` 2.0.0 I've got a compilation error stating that `fromEvents` doesn't exists in a class that subclasses from Socket:

```
ERROR in xxxx/xxx-component.ts(24,27): error TS2339: Property 'fromEvent' does not exist on type 'WebSocketService'.
```

If I edit that file and save it without changing anything, then the error is raised again, but finally it compiles and the app runs. I'm running `ng serve`.
 
It looks like some kind of packaging issue that prevents the module from being imported the at the first time.

Same behavior using both `ng serve` and `ng serve --aot`.

**Comment by bougarfaoui** [comment]
Sorry for being late, this is weird I works very well for me.  where does WebSocketService come from ?
