### ISSUE TITLE
Any plans to make it available for angular version 4?

### ISSUE THREAD

**Issue by ffreitasit** [bougarfaoui/ng-socket-io#5]
Any plans to make it available for angular version 4?

**Comment by bougarfaoui** [comment]
yeah, I just need to find time to do it

**Comment by JoelParke** [comment]
What are the issues for angular 4?? And where to look at the problem?  Is it documented?

**Comment by bougarfaoui** [comment]
@JoelParke there is no issues for angular 4 just update angular 2 dependencies in package.json to the angular 4 ones, or just copy `socket-io.module.ts`, `socket-io.service.ts` and ` socketIoConfig.ts `into your project and `npm install socket.io --save`.

**Comment by bougarfaoui** [comment]
now the module is Angular 4 compatible, I will close this issue, feel free to reopen it if you have a problem.
