### ISSUE TITLE
Compilation on Ionic

### ISSUE THREAD

**Issue by Limoli** [bougarfaoui/ng-socket-io#6]
Compiling my **Ionic application** with your plugin in production mode I always get the following error:

```
Error: Error encountered resolving symbol values statically. 
Calling function 'makeDecorator', function calls are not supported. 
Consider replacing the function or lambda with a reference to an exported function, 
resolving symbol Injectable in 

node_modules/ng2-socket-io/node_modules/@angular/core/src/di/metadata.d.ts,

resolving symbol OpaqueToken in 

node_modules/ng2-socket-io/node_modules/@angular/core/src/di/opaque_token.d.ts, 

resolving symbol OpaqueToken in 

node_modules/ng2-socket-io/node_modules/@angular/core/src/di/opaque_token.d.ts
```

**Comment by bougarfaoui** [comment]
is it working in development mode ?

**Comment by mashhoodr** [comment]
@bougarfaoui yes working in development mode this issue is related to AOT compiler.

**Comment by narainsagar** [comment]
@bougarfaoui @Limoli I think, In the library `package.json` file -  moving all "@angular/*" to `peerDependencies` may solve the issue.
```
"peerDependencies": {
    "@angular/common": ">=4.1.3",
    "@angular/compiler": ">=4.1.3",
    "@angular/compiler-cli": ">=4.1.3",
    "@angular/core": ">=4.1.3",
    "@angular/platform-browser": ">=4.1.3",
    "@angular/platform-browser-dynamic": ">=4.1.3"
  },
```

**Comment by mashhoodr** [comment]
Thanks @narainsagar I got it working by moving to the ng-socket-io package from ng2-socket-io - working fine now!

**Comment by Limoli** [comment]
@narainsagar Moving Angular dependencies under peerDependencies didn't solve the problem. 
@mashhoodr How did you fix it?

**Comment by mashhoodr** [comment]
@Limoli I updated to the newer npm package (from ng2-socket-io to ng-socket-io) - just remove and readd it should work.

**Comment by AmitPhulera** [comment]
I started with ng-socket-io, it still throws error with --aot .
Any updates on it?

**Comment by bougarfaoui** [comment]
@AmitPhulera  I just updated the module, and I compiled using --aot and it works fine.
I will close the issue, if anyone have any problem feel free to open it again , sorry for being late.
